# Generated by Django 6.0.1 on 2026-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="date_pub",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
