# Generated by Django 6.0.1 on 2026-01-07 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_gallery_date_pub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="date_pub",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
