# Generated by Django 6.0.1 on 2026-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_gallery_date_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="description",
            field=models.TextField(default="booyah"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(default=110869431, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="price",
            field=models.DecimalField(decimal_places=2, default=35, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.CharField(default="ggrsggs", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="title",
            field=models.CharField(default="hsgsgsgs", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(max_length=50),
        ),
    ]
