# Generated by Django 6.0.1 on 2026-01-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_appointment_description_appointment_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="title",
        ),
    ]
