# Generated by Django 6.0.1 on 2026-01-13 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_appointment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date_booked",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
