# Generated by Django 6.0.1 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_appointment_date_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
